version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/fullmarks
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  postbuild:
    - location: scripts/postbuild
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
