const userRouter = require("./adminpanel/users");
const publicRouter = require("./adminpanel/publicRoute");
const customerRouter = require("./adminpanel/customers");
const subjectRouter = require("./adminpanel/questions/subjects");
const topicRouter = require("./adminpanel/questions/topics");
const questionRouter = require("./adminpanel/questions/questions");
const mockRouter = require("./adminpanel/questions/mockMaster");
const mockQuestionsRouter = require("./adminpanel/questions/mockQuestions");
const appUser = require("./application/appUser");
const setsRouter = require("./adminpanel/questions/sets");
const mockSets = require("./adminpanel/questions/mockSets");
const liveQuizRouter = require("./application/liveQuiz/liveQuiz");
const customQuiz = require("./application/customQuiz/customQuiz");
const postsRouter = require("./application/discussion/posts");
const commentRouter = require("./application/discussion/comments");
const classRouter = require("./adminpanel/questions/class");
const pageValidation = require("./adminpanel/pageValidation");
const reportRouter = require("./adminpanel/questions/report");
const addQuestionByExcel = require("./adminpanel/questions/addQuestionByExcel");
const notificationRouter = require("./adminpanel/sendNotification");
const friendsRouter = require("./application/friends/friends");
require("./application/activity/activity");

module.exports = (app) => {
  app.use("/", publicRouter);
  app.use("/users", userRouter);
  app.use("/customer", customerRouter);
  app.use("/class", classRouter);
  app.use("/subjects", subjectRouter);
  app.use("/subjects", topicRouter);
  app.use("/subjects/topics/sets", setsRouter);
  app.use("/questions", questionRouter);
  app.use("/app/customer", appUser);
  app.use("/mockQuestions", mockQuestionsRouter);
  app.use("/mock", mockRouter);
  app.use("/mock/sets", mockSets);
  app.use("/live", liveQuizRouter);
  app.use("/live/custom", customQuiz);
  app.use("/posts", postsRouter);
  app.use("/posts/comments", commentRouter);
  app.use("/pageValidation", pageValidation);
  app.use("/report", reportRouter);
  app.use("/addQuestion", addQuestionByExcel);
  app.use("/notification", notificationRouter);
  app.use("/friends", friendsRouter);
};
