export const codes = {
  Accents: [
    String.raw`a'`,
    String.raw`\tilde{a}`,
    String.raw`\mathring{a}`,
    String.raw`a''`,
    String.raw`\widetilde{ac}`,
    String.raw`\overgroup{AB}`,
    String.raw`a^{\prime}`,
    String.raw`\utilde{AB}`,
    String.raw`\undergroup{AB}`,
    String.raw`\acute{a}`,
    String.raw`\vec{F}`,
    String.raw`\overrightarrow{AB}`,
    String.raw`\bar{y}`,
    String.raw`\overleftarrow{AB}`,
    String.raw`\overrightarrow{AB}`,
    String.raw`\breve{a}`,
    String.raw`\underleftarrow{AB}`,
    String.raw`\underrightarrow{AB}`,
    String.raw`\check{a}`,
    String.raw`\overleftharpoon{ac}`,
    String.raw`\overrightharpoon{ac}`,
    String.raw`\dot{a}`,
    String.raw`\overleftrightarrow{AB}`,
    String.raw`\overbrace{AB}`,
    String.raw`\ddot{a}`,
    String.raw`\underleftrightarrow{AB}`,
    String.raw`\underbrace{AB}`,
    String.raw`\grave{a}`,
    String.raw`\overline{AB}`,
    String.raw`\overlinesegment{AB}`,
    String.raw`\hat{\theta}`,
    String.raw`\underline{AB}`,
    String.raw`\underlinesegment{AB}`,
    String.raw`\widehat{ac}`,
    // String.raw`\widecheck{ac}`,
  ],
  Delimiters: [
    String.raw`(~)`,
    String.raw`\lceil~\rceil`,
    String.raw`\uparrow`,
    String.raw`[~]`,
    String.raw`\lfloor~\rfloor`,
    String.raw`\downarrow`,
    String.raw`\{ \}`,
    String.raw`\lbrace \rbrace`,
    String.raw`\lmoustache \rmoustache`,
    String.raw`\updownarrow`,
    String.raw`\langle~\rangle`,
    String.raw`\lgroup~\rgroup`,
    String.raw`\Uparrow`,
    String.raw`\vert`,
    String.raw`\ulcorner \urcorner`,
    String.raw`\Downarrow`,
    String.raw`\Vert`,
    String.raw`\llcorner \lrcorner`,
    String.raw`\Updownarrow`,
    String.raw`\lvert~\rvert`,
    String.raw`\lVert~\rVert`,
    String.raw`\backslash`,
    // String.raw`\lang~\rang`,
    String.raw`\lt~\gt`,
    // String.raw`\llbracket~\rrbracket`,
    // String.raw`\lBrace~\rBrace`,
  ],
  "Delimiter Sizing": [
    String.raw`\left(\LARGE{AB}\right)`,
    String.raw`( \big( \Big( \bigg( \Bigg(`,
  ],
  Environment: [
    String.raw`\begin{matrix} a & b \\ c & d \end{matrix}`,
    String.raw`\begin{array}{cc}a & b\\c & d\end{array}`,
    String.raw`\begin{pmatrix} a & b \\ c & d \end{pmatrix}`,
    String.raw`\begin{bmatrix} a & b \\ c & d \end{bmatrix}`,
    String.raw`\begin{vmatrix} a & b \\ c & d \end{vmatrix}`,
    String.raw`\begin{Vmatrix} a & b \\ c & d \end{Vmatrix}`,
    String.raw`\begin{Bmatrix} a & b \\ c & d \end{Bmatrix}`,
    // String.raw`\def\arraystretch{1.5}\begin{array}{c:c:c} a & b & c \\ \hline d & e & f \\ \hdashline g & h & i \end{array}`,
    // String.raw`\begin{array}{c:c:c} a & b & c \\ \hline d & e & f \\ \hdashline g & h & i \end{array}`,
    String.raw`\begin{aligned} a&=b+c \\ d+e&=f \end{aligned}`,
    String.raw`\begin{alignedat}{2}10&x+&3&y=2\\3&x+&13&y=4\end{alignedat}`,
    String.raw`\begin{gathered} a=b \\ e=b+c \end{gathered}`,
    String.raw`x = \begin{cases} a &\text{if } b \\ c &\text{if } d \end{cases}`,
    //    String.raw`\begin{rcases} a &\text{if } b \\ c &\text{if } d \end{rcases}⇒…`,
  ],

  "Greek Letters": [
    String.raw`\alpha`,
    String.raw`\beta`,
    String.raw`\Gamma`,
    String.raw`\Delta`,
    String.raw`\epsilon`,
    String.raw`\zeta`,
    String.raw`\eta`,
    String.raw`\Theta`,
    String.raw`\iota`,
    String.raw`\kappa`,
    String.raw`\Lambda`,
    String.raw`\mu`,
    String.raw`\nu`,
    String.raw`\Xi`,
    String.raw`\omicron`,
    String.raw`\Pi`,
    String.raw`\rho`,
    String.raw`\Sigma`,
    String.raw`\tau`,
    String.raw`\Upsilon`,
    String.raw`\Phi`,
    String.raw`\chi`,
    String.raw`\Psi`,
    String.raw`\Omega`,
    String.raw`\varGamma`,
    String.raw`\varDelta`,
    String.raw`\varTheta`,
    String.raw`\varLambda`,
    String.raw`\varXi`,
    String.raw`\varPi`,
    String.raw`\varSigma`,
    String.raw`\varUpsilon`,
    String.raw`\varPhi`,
    String.raw`\varPsi`,
    String.raw`\varOmega`,
    String.raw`\alpha`,
    String.raw`\beta`,
    String.raw`\gamma`,
    String.raw`\delta`,
    String.raw`\epsilon`,
    String.raw`\zeta`,
    String.raw`\eta`,
    String.raw`\theta`,
    String.raw`\iota`,
    String.raw`\kappa`,
    String.raw`\lambda`,
    String.raw`\mu`,
    String.raw`\nu`,
    String.raw`\xi`,
    String.raw`\omicron`,
    String.raw`\pi`,
    String.raw`\rho`,
    String.raw`\sigma`,
    String.raw`\tau`,
    String.raw`\upsilon`,
    String.raw`\phi`,
    String.raw`\chi`,
    String.raw`\psi`,
    String.raw`\omega`,
    String.raw`\varepsilon`,
    String.raw`\varkappa`,
    String.raw`\vartheta`,
    // String.raw`\Thetasym`,
    String.raw`\varpi`,
    String.raw`\varrho`,
    String.raw`\varsigma`,
    String.raw`\varphi`,
    String.raw`\digamma`,
  ],

  "Other characters": [
    String.raw`\imath`,
    String.raw`\nabla`,
    String.raw`\Im`,
    // String.raw`\Reals`,
    String.raw`\text{\OE}`,
    String.raw`\jmath`,
    String.raw`\partial`,
    // String.raw`\image`,
    String.raw`\wp`,
    String.raw`\text{\o}`,
    String.raw`\aleph`,
    String.raw`\Game`,
    String.raw`\Bbbk`,
    // String.raw`\weierp`,
    String.raw`\text{\O}`,
    // String.raw`\alef`,
    String.raw`\Finv`,
    // String.raw`\N`,
    // String.raw`\Z`,
    String.raw`\text{\ss}`,
    // String.raw`\alefsym`,
    // String.raw`\cnums`,
    // String.raw`\natnums`,
    String.raw`\text{\aa}`,
    String.raw`\text{\i}`,
    String.raw`\beth`,
    // String.raw`\complex`,
    // String.raw`\R`,
    String.raw`\text{\AA}`,
    String.raw`\text{\j}`,
    String.raw`\gimel`,
    String.raw`\ell`,
    String.raw`\Re`,
    String.raw`\text{\ae}`,
    String.raw`\daleth`,
    String.raw`\hbar`,
    // String.raw`\real`,
    String.raw`\text{\AE}`,
    String.raw`\eth`,
    String.raw`\hslash`,
    // String.raw`\reals`,
    String.raw`\text{\oe}`,
  ],
  //   "Unicode Mathematical Alphanumeric Symbols": [
  //     String.raw`\text{𝐀-𝐙 𝐚-𝐳 𝟎-𝟗}`,
  //     String.raw`\text{𝔸-}ℤ\ 𝕜`,
  //     String.raw`\text{𝐴-𝑍 𝑎-𝑧}`,
  //     String.raw`\text{𝖠-𝖹 𝖺-𝗓 𝟢-𝟫}`,
  //     String.raw`\text{𝑨-𝒁 𝒂-𝒛}`,
  //     String.raw`\text{𝗔-𝗭 𝗮-𝘇 𝟬-𝟵}`,
  //     String.raw`\text{𝒜-𝒵}`,
  //     String.raw`\text{𝘈-𝘡 𝘢-𝘻}`,
  //     String.raw`\text{𝔄-}ℨ\text{ 𝔞-𝔷}`,
  //     String.raw`\text{𝙰-𝚉 𝚊-𝚣 𝟶-𝟿}`,
  //   ],
  "Layout - Annotation": [
    String.raw`\cancel{5}`,
    String.raw`\overbrace{a+b+c}^{\text{note}}`,
    String.raw`\bcancel{5}`,
    String.raw`\underbrace{a+b+c}_{\text{note}}`,
    String.raw`\xcancel{ABC}`,
    String.raw`\not =`,
    String.raw`\sout{abc}`,
    String.raw`\boxed{\pi=\frac c d}`,
    // r'\tag{hi} x+y^{2x}',
    // r'\tag*{hi} x+y^{2x}',
  ],
  "Layout - Vertical Layout": [
    String.raw`x_n`,
    String.raw`\stackrel{!}{=}`,
    String.raw`a \atop b`,
    String.raw`e^x`,
    String.raw`\overset{!}{=}`,
    String.raw`a\raisebox{0.25em}{b}c`,
    String.raw`_u^o `,
    String.raw`\underset{!}{=}`,
    //    String.raw`\sum_{\substack{0<i<m\\0<j<n}}`,
  ],
  "Logic and Set Theory": [
    String.raw`\forall`,
    String.raw`\complement`,
    String.raw`\therefore`,
    String.raw`\emptyset`,
    String.raw`\exists`,
    String.raw`\subset`,
    String.raw`\because`,
    // String.raw`\empty`,
    // String.raw`\exist`,
    String.raw`\supset`,
    String.raw`\mapsto`,
    String.raw`\varnothing`,
    String.raw`\nexists`,
    String.raw`\mid`,
    String.raw`\to`,
    String.raw`\implies`,
    String.raw`\in`,
    String.raw`\land`,
    String.raw`\gets`,
    String.raw`\impliedby`,
    String.raw`\in`,
    String.raw`\lor`,
    String.raw`\leftrightarrow`,
    String.raw`\iff`,
    String.raw`\notin`,
    String.raw`\ni`,
    String.raw`\notni`,
    String.raw`\neg`,
  ],
  // 'Macros': [
  //   r'\def\foo{x^2} \foo + \foo',
  //   r'\gdef\bar#1{#1^2} \bar{y} + \bar{y}',
  // ],
  "Big Operators": [
    String.raw`\sum`,
    String.raw`\prod`,
    String.raw`\bigotimes`,
    String.raw`\bigvee`,
    String.raw`\int`,
    String.raw`\coprod`,
    String.raw`\bigoplus`,
    String.raw`\bigwedge`,
    String.raw`\iint`,
    String.raw`\intop`,
    String.raw`\bigodot`,
    String.raw`\bigcap`,
    String.raw`\iiint`,
    String.raw`\smallint`,
    String.raw`\biguplus`,
    String.raw`\bigcup`,
    String.raw`\oint`,
    String.raw`\oint \hspace{-11pt} \int`,
    // String.raw`\oiiint`,
    String.raw`\bigsqcup`,
  ],

  "Binary Operator": [
    String.raw`+`,
    String.raw`\cdot`,
    String.raw`\gtrdot`,
    String.raw`x \pmod a`,
    String.raw`-`,
    String.raw`\cdotp`,
    String.raw`\intercal`,
    String.raw`x \pod a`,
    String.raw`/`,
    String.raw`\centerdot`,
    String.raw`\land`,
    String.raw`\rhd`,
    String.raw`*`,
    String.raw`\circ`,
    String.raw`\leftthreetimes`,
    String.raw`\rightthreetimes`,
    String.raw`\amalg`,
    String.raw`\circledast`,
    String.raw`\ldotp`,
    String.raw`\rtimes`,
    String.raw`\And`,
    String.raw`\circledcirc`,
    String.raw`\lor`,
    String.raw`\setminus`,
    String.raw`\ast`,
    String.raw`\circleddash`,
    String.raw`\lessdot`,
    String.raw`\smallsetminus`,
    String.raw`\barwedge`,
    String.raw`\Cup`,
    String.raw`\lhd`,
    String.raw`\sqcap`,
    String.raw`\bigcirc`,
    String.raw`\cup`,
    String.raw`\ltimes`,
    String.raw`\sqcup`,
    String.raw`\bmod`,
    String.raw`\curlyvee`,
    String.raw`x \mod a`,
    String.raw`\times`,
    String.raw`\boxdot`,
    String.raw`\curlywedge`,
    String.raw`\mp`,
    String.raw`\unlhd`,
    String.raw`\boxminus`,
    String.raw`\div`,
    String.raw`\odot`,
    String.raw`\unrhd`,
    String.raw`\boxplus`,
    String.raw`\divideontimes`,
    String.raw`\ominus`,
    String.raw`\uplus`,
    String.raw`\boxtimes`,
    String.raw`\dotplus`,
    String.raw`\oplus`,
    String.raw`\vee`,
    String.raw`\bullet`,
    String.raw`\doublebarwedge`,
    String.raw`\otimes`,
    String.raw`\veebar`,
    String.raw`\Cap`,
    String.raw`\doublecap`,
    String.raw`\oslash`,
    String.raw`\wedge`,
    String.raw`\cap`,
    String.raw`\doublecup`,
    String.raw`\pm`,
    String.raw`\wr`,
  ],
  "Fractions and Binomials": [
    String.raw`\frac{a}{b}`,
    String.raw`\tfrac{a}{b}`,
    // String.raw`\genfrac ( ] {2pt}{1}a{a+1}`,
    String.raw`{a \over b}`,
    String.raw`\dfrac{a}{b}`,
    // String.raw`{a \above{2pt} b+1}`,
    String.raw`a/b`,
    String.raw`{a \over {1 + a\over b}}`,
    String.raw`{a \over {1 + {a\over b}}}`,
    String.raw`\binom{n}{k}`,
    String.raw`\dbinom{n}{k}`,
    // String.raw`{n \brace k}`,
    String.raw`{n \choose k}`,
    // String.raw`{n \brack k}`,
  ],
  "Math Operators": [
    String.raw`\arcsin`,
    String.raw`\cotg`,
    String.raw`\ln`,
    String.raw`\det`,
    String.raw`\arccos`,
    String.raw`\coth`,
    String.raw`\log`,
    String.raw`\gcd`,
    String.raw`\arctan`,
    String.raw`\csc`,
    String.raw`\sec`,
    String.raw`\inf`,
    String.raw`\arctg`,
    String.raw`\ctg`,
    String.raw`\sin`,
    String.raw`\lim`,
    String.raw`\arcctg`,
    String.raw`\cth`,
    String.raw`\sinh`,
    String.raw`\liminf`,
    String.raw`\arg`,
    String.raw`\deg`,
    String.raw`\sh`,
    String.raw`\limsup`,
    String.raw`\ch`,
    String.raw`\dim`,
    String.raw`\tan`,
    String.raw`\max`,
    String.raw`\cos`,
    String.raw`\exp`,
    String.raw`\tanh`,
    String.raw`\min`,
    String.raw`\cosec`,
    String.raw`\hom`,
    String.raw`\tg`,
    String.raw`\Pr`,
    String.raw`\cosh`,
    String.raw`\ker`,
    String.raw`\th`,
    String.raw`\sup`,
    String.raw`\cot`,
    String.raw`\lg`,
    // String.raw`\argmax`,
    // String.raw`\argmin`,
    // String.raw`\plim`,
    String.raw`\operatorname{f}`,
    String.raw`\operatorname*{f}`,
    String.raw`\sqrt{x}`,
    String.raw`\sqrt[3]{x}`,
  ],

  Relations: [
    String.raw`=`,
    String.raw`\eqcirc`,
    String.raw`\lesseqgtr`,
    String.raw`\sqsupset`,
    String.raw`<`,
    String.raw`\eqcolon`,
    String.raw`\lesseqqgtr`,
    String.raw`\sqsupseteq`,
    String.raw`>`,
    String.raw`\Eqcolon`,
    String.raw`\lessgtr`,
    String.raw`\Subset`,
    String.raw`:`,
    String.raw`\eqqcolon`,
    String.raw`\lesssim`,
    String.raw`\subset`,
    String.raw`\approx`,
    String.raw`\Eqqcolon`,
    String.raw`\ll`,
    String.raw`\subseteq`,
    String.raw`\approxeq`,
    String.raw`\eqsim`,
    String.raw`\lll`,
    String.raw`\subseteqq`,
    String.raw`\asymp`,
    String.raw`\eqslantgtr`,
    String.raw`\llless`,
    String.raw`\succ`,
    String.raw`\backepsilon`,
    String.raw`\eqslantless`,
    String.raw`\lt`,
    String.raw`\succapprox`,
    String.raw`\backsim`,
    String.raw`\equiv`,
    String.raw`\mid`,
    String.raw`\succcurlyeq`,
    String.raw`\backsimeq`,
    String.raw`\fallingdotseq`,
    String.raw`\models`,
    String.raw`\succeq`,
    String.raw`\between`,
    String.raw`\frown`,
    String.raw`\multimap`,
    String.raw`\succsim`,
    String.raw`\bowtie`,
    String.raw`\ge`,
    String.raw`\owns`,
    String.raw`\Supset`,
    String.raw`\bumpeq`,
    String.raw`\geq`,
    String.raw`\parallel`,
    String.raw`\supset`,
    String.raw`\Bumpeq`,
    String.raw`\geqq`,
    String.raw`\perp`,
    String.raw`\supseteq`,
    String.raw`\circeq`,
    String.raw`\geqslant`,
    String.raw`\pitchfork`,
    String.raw`\supseteqq`,
    String.raw`\colonapprox`,
    String.raw`\gg`,
    String.raw`\prec`,
    String.raw`\thickapprox`,
    String.raw`\Colonapprox`,
    String.raw`\ggg`,
    String.raw`\precapprox`,
    String.raw`\thicksim`,
    String.raw`\coloneq`,
    String.raw`\gggtr`,
    String.raw`\preccurlyeq`,
    String.raw`\trianglelefteq`,
    String.raw`\Coloneq`,
    String.raw`\gt`,
    String.raw`\preceq`,
    String.raw`\triangleq`,
    String.raw`\coloneqq`,
    String.raw`\gtrapprox`,
    String.raw`\precsim`,
    String.raw`\trianglerighteq`,
    String.raw`\Coloneqq`,
    String.raw`\gtreqless`,
    String.raw`\propto`,
    String.raw`\varpropto`,
    String.raw`\colonsim`,
    String.raw`\gtreqqless`,
    String.raw`\risingdotseq`,
    String.raw`\vartriangle`,
    String.raw`\Colonsim`,
    String.raw`\gtrless`,
    String.raw`\shortmid`,
    String.raw`\vartriangleleft`,
    String.raw`\cong`,
    String.raw`\gtrsim`,
    String.raw`\shortparallel`,
    String.raw`\vartriangleright`,
    String.raw`\curlyeqprec`,
    String.raw`\in`,
    String.raw`\sim`,
    String.raw`\vcentcolon`,
    String.raw`\curlyeqsucc`,
    String.raw`\Join`,
    String.raw`\simeq`,
    String.raw`\vdash`,
    String.raw`\dashv`,
    String.raw`\le`,
    String.raw`\smallfrown`,
    String.raw`\vDash`,
    String.raw`\dblcolon`,
    String.raw`\leq`,
    String.raw`\smallsmile`,
    String.raw`\Vdash`,
    String.raw`\doteq`,
    String.raw`\leqq`,
    String.raw`\smile`,
    String.raw`\Vvdash`,
    String.raw`\Doteq`,
    String.raw`\leqslant`,
    String.raw`\sqsubset`,
    String.raw`\doteqdot`,
    String.raw`\lessapprox`,
    String.raw`\sqsubseteq`,
  ],

  "Negated Relations": [
    String.raw`\gnapprox`,
    String.raw`\ngeqslant`,
    String.raw`\nsubseteq`,
    String.raw`\precneqq`,
    String.raw`\gneq`,
    String.raw`\ngtr`,
    String.raw`\nsubseteqq`,
    String.raw`\precnsim`,
    String.raw`\gneqq`,
    String.raw`\nleq`,
    String.raw`\nsucc`,
    String.raw`\subsetneq`,
    String.raw`\gnsim`,
    String.raw`\nleqq`,
    String.raw`\nsucceq`,
    String.raw`\subsetneqq`,
    String.raw`\gvertneqq`,
    String.raw`\nleqslant`,
    String.raw`\nsupseteq`,
    String.raw`\succnapprox`,
    String.raw`\lnapprox`,
    String.raw`\nless`,
    String.raw`\nsupseteqq`,
    String.raw`\succneqq`,
    String.raw`\lneq`,
    String.raw`\nmid`,
    String.raw`\ntriangleleft`,
    String.raw`\succnsim`,
    String.raw`\lneqq`,
    String.raw`\notin`,
    String.raw`\ntrianglelefteq`,
    String.raw`\supsetneq`,
    String.raw`\lnsim`,
    String.raw`\notni`,
    String.raw`\ntriangleright`,
    String.raw`\supsetneqq`,
    String.raw`\lvertneqq`,
    String.raw`\nparallel`,
    String.raw`\ntrianglerighteq`,
    String.raw`\varsubsetneq`,
    String.raw`\ncong`,
    String.raw`\nprec`,
    String.raw`\nvdash`,
    String.raw`\varsubsetneqq`,
    String.raw`\ne`,
    String.raw`\npreceq`,
    String.raw`\nvDash`,
    String.raw`\varsupsetneq`,
    String.raw`\neq`,
    String.raw`\nshortmid`,
    String.raw`\nVDash`,
    String.raw`\varsupsetneqq`,
    String.raw`\ngeq`,
    String.raw`\nshortparallel`,
    String.raw`\nVdash`,
    String.raw`\ngeqq`,
    String.raw`\nsim`,
    String.raw`\precnapprox`,
  ],

  Arrows: [
    String.raw`\circlearrowleft`,
    String.raw`\leftharpoonup`,
    // String.raw`\rArr`,
    String.raw`\circlearrowright`,
    String.raw`\leftleftarrows`,
    // String.raw`\rarr`,
    String.raw`\curvearrowleft`,
    String.raw`\leftrightarrow`,
    String.raw`\restriction`,
    String.raw`\curvearrowright`,
    String.raw`\Leftrightarrow`,
    String.raw`\rightarrow`,
    // String.raw`\Darr`,
    String.raw`\leftrightarrows`,
    String.raw`\Rightarrow`,
    // String.raw`\dArr`,
    String.raw`\leftrightharpoons`,
    String.raw`\rightarrowtail`,
    // String.raw`\darr`,
    String.raw`\leftrightsquigarrow`,
    String.raw`\rightharpoondown`,
    String.raw`\dashleftarrow`,
    String.raw`\Lleftarrow`,
    String.raw`\rightharpoonup`,
    String.raw`\dashrightarrow`,
    String.raw`\longleftarrow`,
    String.raw`\rightleftarrows`,
    String.raw`\downarrow`,
    String.raw`\Longleftarrow`,
    String.raw`\rightleftharpoons`,
    String.raw`\Downarrow`,
    String.raw`\longleftrightarrow`,
    String.raw`\rightrightarrows`,
    String.raw`\downdownarrows`,
    String.raw`\Longleftrightarrow`,
    String.raw`\rightsquigarrow`,
    String.raw`\downharpoonleft`,
    String.raw`\longmapsto`,
    String.raw`\Rrightarrow`,
    String.raw`\downharpoonright`,
    String.raw`\longrightarrow`,
    String.raw`\Rsh`,
    String.raw`\gets`,
    String.raw`\Longrightarrow`,
    String.raw`\searrow`,
    // String.raw`\Harr`,
    String.raw`\looparrowleft`,
    String.raw`\swarrow`,
    // String.raw`\hArr`,
    String.raw`\looparrowright`,
    String.raw`\to`,
    // String.raw`\harr`,
    // String.raw`\Lrarr`,
    String.raw`\twoheadleftarrow`,
    String.raw`\hookleftarrow`,
    // String.raw`\lrArr`,
    String.raw`\twoheadrightarrow`,
    String.raw`\hookrightarrow`,
    // String.raw`\lrarr`,
    // String.raw`\Uarr`,
    String.raw`\iff`,
    String.raw`\Lsh`,
    // String.raw`\uArr`,
    String.raw`\impliedby`,
    String.raw`\mapsto`,
    // String.raw`\uarr`,
    String.raw`\implies`,
    String.raw`\nearrow`,
    String.raw`\uparrow`,
    // String.raw`\Larr`,
    String.raw`\nleftarrow`,
    String.raw`\Uparrow`,
    // String.raw`\lArr`,
    String.raw`\nLeftarrow`,
    String.raw`\updownarrow`,
    // String.raw`\larr`,
    String.raw`\nleftrightarrow`,
    String.raw`\Updownarrow`,
    String.raw`\leadsto`,
    String.raw`\nLeftrightarrow`,
    String.raw`\upharpoonleft`,
    String.raw`\leftarrow`,
    String.raw`\nrightarrow`,
    String.raw`\upharpoonright`,
    String.raw`\Leftarrow`,
    String.raw`\nRightarrow`,
    String.raw`\upuparrows`,
    String.raw`\leftarrowtail`,
    String.raw`\nwarrow`,
    String.raw`\leftharpoondown`,
    // String.raw`\Rarr`,
  ],
  "Extensible Arrows": [
    String.raw`\xleftarrow{abc}`,
    String.raw`\xrightarrow[under]{over}`,
    String.raw`\xLeftarrow{abc}`,
    String.raw`\xRightarrow{abc}`,
    String.raw`\xleftrightarrow{abc}`,
    String.raw`\xLeftrightarrow{abc}`,
    String.raw`\xhookleftarrow{abc}`,
    String.raw`\xhookrightarrow{abc}`,
    String.raw`\xtwoheadleftarrow{abc}`,
    String.raw`\xtwoheadrightarrow{abc}`,
    String.raw`\xleftharpoonup{abc}`,
    String.raw`\xrightharpoonup{abc}`,
    String.raw`\xleftharpoondown{abc}`,
    String.raw`\xrightharpoondown{abc}`,
    String.raw`\xleftrightharpoons{abc}`,
    String.raw`\xrightleftharpoons{abc}`,
    String.raw`\xtofrom{abc}`,
    String.raw`\xmapsto{abc}`,
    String.raw`\xlongequal{abc}`,
  ],
  //   "Special Notation": [
  //     String.raw`\bra{\phi}`,
  //     String.raw`\ket{\psi}`,
  //     String.raw`\braket{\phi\vert\psi}`,
  //     String.raw`\Bra{\phi}`,
  //     String.raw`\Ket{\psi}`,
  //   ],

  // Class Assignment

  Color: [
    String.raw`\color{blue} F=ma`,
    String.raw`\textcolor{blue}{F=ma}`,
    String.raw`\textcolor{#228B22}{F=ma}`,
    String.raw`\colorbox{aqua}{A}`,
    String.raw`\fcolorbox{red}{aqua}{A}`,
  ],
  Font: [
    String.raw`\mathrm{Ab0}`,
    String.raw`\mathbf{Ab0}`,
    String.raw`\mathit{Ab0}`,
    // String.raw`\mathnormal{Ab0}`,
    String.raw`\textbf{Ab0}`,
    String.raw`\textit{Ab0}`,
    String.raw`\textrm{Ab0}`,
    String.raw`\bf Ab0`,
    String.raw`\it Ab0`,
    String.raw`\rm Ab0`,
    String.raw`\bold{Ab0}`,
    // String.raw`\textup{Ab0}`,
    String.raw`\textnormal{Ab0}`,
    String.raw`\boldsymbol{Ab0}`,
    String.raw`\Bbb{AB}`,
    String.raw`\text{Ab0}`,
    String.raw`\bm{Ab0}`,
    String.raw`\mathbb{AB}`,
    String.raw`\mathsf{Ab0}`,
    // String.raw`\textmd{Ab0}`,
    String.raw`\frak{Ab0}`,
    String.raw`\textsf{Ab0}`,
    String.raw`\mathtt{Ab0}`,
    String.raw`\mathfrak{Ab0}`,
    String.raw`\sf Ab0`,
    String.raw`\texttt{Ab0}`,
    String.raw`\mathcal{AB0}`,
    String.raw`\tt Ab0`,
    // String.raw`\cal AB0`,
    String.raw`\mathscr{AB}`,
  ],
  Size: [
    String.raw`\Huge AB`,
    String.raw`\normalsize AB`,
    String.raw`\huge AB`,
    String.raw`\small AB`,
    String.raw`\LARGE AB`,
    String.raw`\footnotesize AB`,
    String.raw`\Large AB`,
    String.raw`\scriptsize AB`,
    String.raw`\large AB`,
    String.raw`\tiny AB`,
  ],

  Style: [
    String.raw`\displaystyle\sum_{i=1}^n`,
    String.raw`\textstyle\sum_{i=1}^n`,
    String.raw`\scriptstyle x`,
    String.raw`\scriptscriptstyle x`,
    String.raw`\lim\limits_x`,
    String.raw`\lim\nolimits_x`,
    String.raw`\verb!x^2!`,
  ],

  Others: [
    String.raw`\dots`,
    String.raw`\KaTeX`,
    String.raw`\%`,
    String.raw`\cdots`,
    String.raw`\LaTeX`,
    String.raw`\#`,
    String.raw`\ddots`,
    String.raw`\TeX`,
    String.raw`\&`,
    String.raw`\ldots`,
    String.raw`\nabla`,
    String.raw`\_`,
    String.raw`\vdots`,
    String.raw`\infty`,
    String.raw`\text{\textunderscore}`,
    String.raw`\dotsb`,
    String.raw`\text{--}`,
    String.raw`\dotsc`,
    String.raw`\checkmark`,
    String.raw`\text{\textendash}`,
    String.raw`\dotsi`,
    String.raw`\dag`,
    String.raw`\text{---}`,
    String.raw`\dotsm`,
    String.raw`\dagger`,
    String.raw`\text{\textemdash}`,
    String.raw`\dotso`,
    String.raw`\text{\textdagger}`,
    String.raw`\ddag`,
    String.raw`\mathellipsis`,
    String.raw`\ddagger`,
    String.raw`\text{\textellipsis}`,
    String.raw`\text{\textdaggerdbl}`,
    String.raw`\text{\textquoteleft}`,
    String.raw`\Box`,
    String.raw`\lq`,
    String.raw`\square`,
    String.raw`\angle`,
    String.raw`\text{\textquoteright}`,
    String.raw`\blacksquare`,
    String.raw`\measuredangle`,
    String.raw`\rq`,
    String.raw`\triangle`,
    String.raw`\sphericalangle`,
    String.raw`\text{\textquotedblleft}`,
    String.raw`\triangledown`,
    String.raw`\top`,
    String.raw`"`,
    String.raw`\triangleleft`,
    String.raw`\bot`,
    String.raw`\text{\textquotedblright}`,
    String.raw`\triangleright`,
    String.raw`\$`,
    String.raw`\colon`,
    String.raw`\bigtriangledown`,
    String.raw`\text{\textdollar}`,
    String.raw`\backprime`,
    String.raw`\bigtriangleup`,
    String.raw`\pounds`,
    String.raw`\prime`,
    String.raw`\blacktriangle`,
    String.raw`\mathsterling`,
    String.raw`\text{\textless}`,
    String.raw`\blacktriangledown`,
    String.raw`\text{\textsterling}`,
    String.raw`\text{\textgreater}`,
    String.raw`\blacktriangleleft`,
    String.raw`\yen`,
    String.raw`\text{\textbar}`,
    String.raw`\blacktriangleright`,
    String.raw`\surd`,
    String.raw`\text{\textbardbl}`,
    String.raw`\diamond`,
    String.raw`\degree`,
    String.raw`\text{\textbraceleft}`,
    String.raw`\Diamond`,
    String.raw`\text{\textbraceright}`,
    String.raw`\lozenge`,
    String.raw`\mho`,
    String.raw`\blacklozenge`,
    String.raw`\diagdown`,
    String.raw`\text{\P}`,
    String.raw`\star`,
    String.raw`\diagup`,
    String.raw`\text{\S}`,
    String.raw`\bigstar`,
    String.raw`\flat`,
    String.raw`\clubsuit`,
    String.raw`\natural`,
    String.raw`\sharp`,
    String.raw`\circledR`,
    String.raw`\diamondsuit`,
    String.raw`\heartsuit`,
    String.raw`\circledS`,
    String.raw`\spadesuit`,
    String.raw`\maltese`,
  ],
  None: [],
};
